[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "/opt/venv/bin/python manage.py collectstatic --noinput",
  "/opt/venv/bin/python manage.py migrate"
]

[start]
cmd = "/opt/venv/bin/gunicorn hosp_erp2.wsgi --log-file - --workers 2 --bind 0.0.0.0:$PORT"
